# Generated by Django 4.2.2 on 2024-10-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined', '-email'], 'permissions': [('admin', 'Администратор'), ('user', 'Пользователь'), ('manager', 'Менеджер')], 'verbose_name': 'Пользователь сервиса', 'verbose_name_plural': 'Пользователи сервиса'},
        ),
    ]
