# Generated by Django 4.2.2 on 2024-09-04 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='manager_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailmanager.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailmanager.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='manager_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailmanager.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='send_mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailmanager.sendmail', verbose_name='Рассылка'),
        ),
    ]
