# Generated by Django 4.2.2 on 2024-09-10 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailmanager', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendMail',
            new_name='Letter',
        ),
    ]
