# Generated by Django 4.2.2 on 2024-09-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailmanager', '0003_rename_sendmail_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-date_time_send', 'owner', 'status'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='sendattempt',
            options={'ordering': ['-date_time_attempt', 'attempts_count', 'client', 'owner', 'message'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.RenameField(
            model_name='sendattempt',
            old_name='manager_user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='manager_user',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя сервиса (email)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='letter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя сервиса (email)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='clients',
            field=models.ManyToManyField(related_name='letters', to='mailmanager.client', verbose_name='Клиенты'),
        ),
    ]
