# Generated by Django 4.2.2 on 2024-10-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanager', '0007_sendattempt_attempts_count_sendattempt_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendattempt',
            options={'ordering': ['-date_time_attempt'], 'permissions': [('content_manager', 'Может просматривать любые рассылки.'), ('users_list', 'Может просматривать список пользователей сервиса.'), ('block_users', 'Может блокировать пользователей сервиса.'), ('disable_email', 'Может отключать рассылки.'), ('edit_mail', 'Не может редактировать рассылки.'), ('edit_list', 'Не может управлять списком рассылок.'), ('edit_message', 'Не может изменять рассылки и сообщения.')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
    ]
